spring:
   mail:
      host: smtp.gmail.com
      port: 587
      username: fptsosytem@gmail.com
      password: mayconmeo@A
      properties:
         mail:
            smtp:
               starttls:
                  enable: true
