spring:
   application:
      name: sign-fpt
   profiles:
      active: dev
   liquibase: #config for liquibase
      change-log: classpath:/liquibase/changelog/changelog-master.xml
   security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
logging:
   level:
      liquibase: INFO
